### ISSUE TITLE
Add 'publicHealthUnit' to the Site Table

### ISSUE THREAD

**Issue by vipileggi** [Big-Life-Lab/ODM#116]
MECP wants to add 'publicHealthUnit' to the 'Site' table for v1.1.0. We are organizing WS data by PHUs and then sewershed within each PHU so this will facilitate things.

**Comment by DougManuel** [comment]
Sounds good. We'll need to consider the term and description to ensure the language works for settings outside Ontario. public health unit or region works. A clear description will be important.

**Comment by DougManuel** [comment]
I used `publicHealthDepartment` and also added a separate `healthRegion`.

**Comment by NielsNicolai** [comment]
Could you elaborate a bit more on the difference between `publicHealthDepartment` and `healthRegion`? I'm having some difficulties separating the two.
